Testsomething
dla-kirito/hello-world pull request #21
Opened 2022-07-18 09:58 UTC by dla-kirito

2024-03-06 13:03 UTC, ashierj requested changes
111

2024-03-25 10:07 UTC, dla-kirito commented on .github/workflows/crunch42-analysis.yml
> +# Documentation is located here: https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
1

2024-03-25 10:07 UTC, dla-kirito commented on .github/workflows/crunch42-analysis.yml
> +# To use this workflow, you will need to complete the following setup steps.
11

2024-03-29 06:55 UTC, k-xiang commented on .github/workflows/crunch42-analysis.yml
> +# documentation.
测试

2024-03-29 06:56 UTC, k-xiang requested changes
测试

2024-06-05 08:49 UTC, closed without merging